! Generated by tools/gen_vectors.py from the spec's vectors.json. Do not edit.
module tandem_vectors
    use, intrinsic :: iso_fortran_env, only: int32, int64, real32, real64
    implicit none

    type :: t_vector
        integer(int32) :: o(4), h(4), o_out(4), h_out(4)
    end type
    type :: f_vector
        integer(int64) :: counter
        integer(int32) :: o(4), h(4)
    end type
    type :: stream_vector
        integer(int64) :: first_word
        integer(int32) :: words(4)
    end type
    type :: real64_vector
        integer(int64) :: index
        real(real64) :: value
    end type
    type :: real32_vector
        integer(int64) :: index
        real(real32) :: value
    end type
    type :: logical_vector
        integer(int64) :: index
        logical :: value
    end type
    type :: int32_vector
        integer(int64) :: index
        integer(int32) :: value
    end type

    integer(int32), parameter :: VEC_K = 32
    integer(int32), parameter :: VEC_KEY(4) = [int(z'00000001', int32), int(z'00000002', int32), &
            int(z'00000003', int32), int(z'00000004', int32)]
    type(t_vector), parameter :: VEC_T(2) = [ &
        t_vector([int(z'00000001', int32), int(z'00000002', int32), &
            int(z'00000003', int32), int(z'00000004', int32)], &
            [int(z'00000005', int32), int(z'00000006', int32), &
            int(z'00000007', int32), int(z'00000008', int32)], &
            [int(z'00000017', int32), int(z'00150007', int32), &
            int(z'00000001', int32), int(z'00050008', int32)], &
            [int(z'9e377ca9', int32), int(z'0000e006', int32), &
            int(z'02000007', int32), int(z'00001820', int32)]), &
        t_vector([int(z'00000000', int32), int(z'00000000', int32), &
            int(z'00000000', int32), int(z'00000000', int32)], &
            [int(z'00000000', int32), int(z'00000000', int32), &
            int(z'00000000', int32), int(z'00000000', int32)], &
            [int(z'00000000', int32), int(z'00000000', int32), &
            int(z'00000000', int32), int(z'00000000', int32)], &
            [int(z'9e3779b9', int32), int(z'00000000', int32), &
            int(z'00000000', int32), int(z'00000000', int32)])]
    type(f_vector), parameter :: VEC_F(2) = [ &
        f_vector(0_int64, &
            [int(z'472bef12', int32), int(z'c0977c66', int32), &
            int(z'd330ac3a', int32), int(z'b11a020d', int32)], &
            [int(z'bfa0b6ba', int32), int(z'ecdbc48e', int32), &
            int(z'f1989116', int32), int(z'c2374d96', int32)]), &
        f_vector(1_int64, &
            [int(z'b777c10c', int32), int(z'2f6b5a5d', int32), &
            int(z'67a9ce03', int32), int(z'7de06a50', int32)], &
            [int(z'd0c2dc4f', int32), int(z'e1e50e0f', int32), &
            int(z'89efc72c', int32), int(z'6e82b062', int32)])]
    type(stream_vector), parameter :: VEC_STREAM(3) = [ &
        stream_vector(0_int64, &
            [int(z'0a5bcb90', int32), int(z'6dfe98bc', int32), &
            int(z'9612198a', int32), int(z'ac115fd8', int32)]), &
        stream_vector(4_int64, &
            [int(z'33f598d7', int32), int(z'b5c280ca', int32), &
            int(z'7a8e7b99', int32), int(z'8c362290', int32)]), &
        stream_vector(32_int64, &
            [int(z'9da7bac0', int32), int(z'4aca79eb', int32), &
            int(z'beb1f65a', int32), int(z'e2f0d5a1', int32)])]
    type(real64_vector), parameter :: VEC_REAL64(2) = [ &
        real64_vector(0_int64, 0.4296660861094629_real64), &
        real64_vector(16_int64, 0.2921520424112306_real64)]
    type(real32_vector), parameter :: VEC_REAL32(1) = [ &
        real32_vector(2_int64, 0.58621365_real32)]
    type(logical_vector), parameter :: VEC_LOGICAL(9) = [ &
        logical_vector(0_int64, .false.), &
        logical_vector(1_int64, .false.), &
        logical_vector(2_int64, .false.), &
        logical_vector(3_int64, .false.), &
        logical_vector(4_int64, .true.), &
        logical_vector(5_int64, .false.), &
        logical_vector(6_int64, .false.), &
        logical_vector(7_int64, .true.), &
        logical_vector(128_int64, .true.)]
    integer(int32), parameter :: VEC_SPLIT0(4) = [int(z'e256e9a1', int32), int(z'5020f806', int32), &
            int(z'3bd3f7dc', int32), int(z'5328763d', int32)]
    integer(int32), parameter :: VEC_SPLIT1(4) = [int(z'a9ea3f0b', int32), int(z'47f97af0', int32), &
            int(z'd1844c53', int32), int(z'97e9cee2', int32)]
    integer(int32), parameter :: VEC_FORK0(4) = [int(z'67fd37c5', int32), int(z'9dc0b8c6', int32), &
            int(z'4e3bd55e', int32), int(z'af3f2216', int32)]
    integer(int32), parameter :: VEC_PURPOSE7(4) = [int(z'8048398f', int32), int(z'1678e814', int32), &
            int(z'd8823983', int32), int(z'c4b1045c', int32)]
    integer(int64), parameter :: VEC_SEED = 42_int64
    integer(int32), parameter :: VEC_SEED_KEY(4) = [int(z'421d21eb', int32), int(z'32d31777', int32), &
            int(z'62e7564b', int32), int(z'df2bdf82', int32)]
    type(real64_vector), parameter :: VEC_SEED_REAL64(3) = [ &
        real64_vector(0_int64, 0.9829130398628935_real64), &
        real64_vector(2_int64, 0.47759300283385586_real64), &
        real64_vector(16_int64, 0.9692135305890753_real64)]
    type(int32_vector), parameter :: VEC_SEED_INT32(1) = [ &
        int32_vector(0_int64, int(z'05e80cec', int32))]
end module tandem_vectors
