#!/usr/bin/env python3
"""Turn the spec's ziggurat tables into cuda/tandem_zig_tables.f90, value for value.

Fortran has no hexadecimal float literals, so each Float64 is the transfer of its bit pattern.
Usage: tools/gen_zig_tables.py path/to/normal_f64_zig1024.json > cuda/tandem_zig_tables.f90
"""
import hashlib
import json
import struct
import sys

SHA256 = "8b961dd46a2582b953bd8780138edb0ad712e3d243a366a123ffc8978d0a33ab"


def bits(s):
    return struct.unpack("<q", struct.pack("<d", float.fromhex(s)))[0]


def array(name, values, per_line=4, part=256):
    """An int64 parameter array indexed from 0, joined from parts that stay within the 255
    continuation lines of a Fortran statement."""
    out, names = [], []
    for p in range(0, len(values), part):
        items = [f"{v}_int64" for v in values[p:p + part]]
        rows = [", ".join(items[i:i + per_line]) for i in range(0, len(items), per_line)]
        names.append(f"{name}_{p // part}")
        out.append(f"    integer(int64), parameter :: {names[-1]}({len(items)}) = [ &\n        "
                   + ", &\n        ".join(rows) + "]")
    out.append(f"    integer(int64), parameter :: {name}(0:{len(values) - 1}) = [{', '.join(names)}]")
    return "\n".join(out)


def main(path):
    raw = open(path, "rb").read()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != SHA256:
        sys.exit(f"{path}: SHA-256 {digest}, expected {SHA256}")
    t = json.loads(raw)
    n = t["layers"]
    assert n == 1024 and len(t["W"]) == n and len(t["K"]) == n and len(t["Y"]) == n + 1
    assert all(0 <= k < 2**53 for k in t["K"]) and t["K"][-1] == 0
    print("\n".join([
        "! Generated by tools/gen_zig_tables.py from tandem-spec tables/normal_f64_zig1024.json,",
        f"! SHA-256 {SHA256}. Do not edit.",
        "!",
        "! The 1024-layer ziggurat of the Float64 normals (spec Appendix A): the width W(i) and the",
        "! threshold K(i) of layer i and the heights Y, with each Float64 as its bit pattern.",
        "module tandem_zig_tables",
        "    use, intrinsic :: iso_fortran_env, only: int64, real64",
        "    implicit none",
        "    private",
        "    public :: ZIG_R, ZIG_W, ZIG_K, ZIG_Y",
        "",
        array("W_BITS", [bits(w) for w in t["W"]]),
        array("ZIG_K", t["K"]),
        array("Y_BITS", [bits(y) for y in t["Y"]]),
        f"    real(real64), parameter :: ZIG_R = transfer({bits(t['R'])}_int64, 1.0_real64)",
        f"    real(real64), parameter :: ZIG_W(0:{n - 1}) = transfer(W_BITS, 1.0_real64, {n})",
        f"    real(real64), parameter :: ZIG_Y(0:{n}) = transfer(Y_BITS, 1.0_real64, {n + 1})",
        "end module tandem_zig_tables",
    ]))


if __name__ == "__main__":
    main(sys.argv[1])
