#!/usr/bin/env python3
"""Turn tandem-c's cross_*.h fixtures into test/cross.f90, so the tests need no C parser.

The fixtures hold values that core.hpp of tandem-cuda produces for bounded integers and
normals. Usage: tools/gen_cross.py path/to/tandem-c/tests > test/cross.f90
"""
import re
import sys

PER_LINE = {"int32": 6, "int64": 4, "real64": 3, "real32": 4}


def signed(x, bits):
    """The unsigned value as the signed integer with the same bit pattern, as a literal."""
    x = x - (1 << bits) if x >= 1 << (bits - 1) else x
    kind = f"int{bits}"
    if x == -(1 << (bits - 1)):  # the literal 2^(bits-1) overflows before the negation
        return f"(-{-(x + 1)}_{kind} - 1_{kind})"
    return f"{x}_{kind}"


def literal(x, kind):
    if kind.startswith("int"):
        return signed(x, int(kind[3:]))
    return f"{x!r}_{kind}"


def array(name, kind, values, shape):
    """A parameter array, shape given as a Fortran extent list, filled in column-major order."""
    n = PER_LINE[kind]
    items = [literal(v, kind) for v in values]
    rows = [", ".join(items[i:i + n]) for i in range(0, len(items), n)]
    body = ", &\n        ".join(rows)
    if len(shape) == 1:
        return f"    {decl(kind)}, parameter :: {name}({shape[0]}) = [ &\n        {body}]"
    return (f"    {decl(kind)}, parameter :: {name}({', '.join(map(str, shape))}) = reshape([ &\n"
            f"        {body}], &\n        [{', '.join(map(str, shape))}])")


def decl(kind):
    return {"int32": "integer(int32)", "int64": "integer(int64)",
            "real64": "real(real64)", "real32": "real(real32)"}[kind]


def number(text):
    return int(re.sub(r"(ull|u)$", "", text))


def cases(source, name):
    """The (n, want, end_pos) entries of a struct array."""
    block = source.split(f"{name}[] = {{", 1)[1].split("\n};", 1)[0]
    pattern = r"\{(\d+(?:ull|u)),\s*\{([^}]*)\},\s*(\d+(?:ull|u))\}"
    return [(number(n), [number(w) for w in ws.split(",")], number(e))
            for n, ws, e in re.findall(pattern, block)]


def floats(source, name):
    block = source.split(f"{name}[CROSS_NORMAL_COUNT] = {{", 1)[1].split("};", 1)[0]
    return [float(x.strip().rstrip("f")) for x in block.replace("\n", " ").split(",") if x.strip()]


def end_pos(source, name):
    return int(re.search(rf"{name} = (\d+)u;", source).group(1))


def main(directory):
    below = open(f"{directory}/cross_below.h").read()
    fill = open(f"{directory}/cross_fill_below.h").read()
    normal = open(f"{directory}/cross_normal.h").read()
    count = int(re.search(r"CROSS_COUNT (\d+)", below).group(1))
    assert count == int(re.search(r"CROSS_NORMAL_COUNT (\d+)", normal).group(1))

    out = [
        "! Generated by tools/gen_cross.py from tandem-c's tests/cross_*.h. Do not edit.",
        "module tandem_cross",
        "    use, intrinsic :: iso_fortran_env, only: int32, int64, real32, real64",
        "    implicit none",
        "",
        f"    integer, parameter :: CROSS_COUNT = {count}",
    ]
    for prefix, source, tag in (("BELOW", below, "CROSS"), ("FILL_BELOW", fill, "CROSS_FILL")):
        for bits in (32, 64):
            entries = cases(source, f"{tag}_U{bits}")
            kind = f"int{bits}"
            m = len(entries)
            out.append(array(f"CROSS_{prefix}{bits}_N", kind, [e[0] for e in entries], [m]))
            out.append(array(f"CROSS_{prefix}{bits}_WANT", kind,
                             [w for e in entries for w in e[1]], [count, m]))
            out.append(array(f"CROSS_{prefix}{bits}_END", "int64", [e[2] for e in entries], [m]))
    out.append(array("CROSS_NORMAL", "real64", floats(normal, "CROSS_NORMAL"), [count]))
    out.append(f"    integer(int64), parameter :: CROSS_NORMAL_END = "
               f"{end_pos(normal, 'CROSS_NORMAL_END_POS')}_int64")
    out.append(array("CROSS_NORMALF", "real32", floats(normal, "CROSS_NORMALF"), [count]))
    out.append(f"    integer(int64), parameter :: CROSS_NORMALF_END = "
               f"{end_pos(normal, 'CROSS_NORMALF_END_POS')}_int64")
    out.append("end module tandem_cross")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
