#!/usr/bin/env python3
"""Turn the spec's vectors.json into test/vectors.f90, so the tests need no JSON parser.

Usage: tools/gen_vectors.py path/to/vectors.json > test/vectors.f90
"""
import json
import sys


def word(w):
    return f"int(z'{w}', int32)"


def words(ws):
    """Four words, two per line, to stay inside the 132-column limit."""
    half = [", ".join(word(w) for w in ws[i:i + 2]) for i in (0, 2)]
    return "[" + half[0] + ", &\n            " + half[1] + "]"


def array(name, decl, items):
    """A parameter array, one item per continuation line."""
    lines = [f"    {decl}, parameter :: {name}({len(items)}) = [ &"]
    lines += [f"        {x}, &" for x in items[:-1]]
    lines.append(f"        {items[-1]}]")
    return lines


def ctor(name, args):
    """A structure constructor with one argument per line."""
    return name + "(" + ", &\n            ".join(args) + ")"


def real64(x):
    return f"{x!r}_real64"


def real32(x):
    return f"{x!r}_real32"


def main(path):
    v = json.load(open(path))
    out = [
        "! Generated by tools/gen_vectors.py from the spec's vectors.json. Do not edit.",
        "module tandem_vectors",
        "    use, intrinsic :: iso_fortran_env, only: int32, int64, real32, real64",
        "    implicit none",
        "",
        "    type :: t_vector",
        "        integer(int32) :: o(4), h(4), o_out(4), h_out(4)",
        "    end type",
        "    type :: f_vector",
        "        integer(int64) :: counter",
        "        integer(int32) :: o(4), h(4)",
        "    end type",
        "    type :: stream_vector",
        "        integer(int64) :: first_word",
        "        integer(int32) :: words(4)",
        "    end type",
        "    type :: real64_vector",
        "        integer(int64) :: index",
        "        real(real64) :: value",
        "    end type",
        "    type :: real32_vector",
        "        integer(int64) :: index",
        "        real(real32) :: value",
        "    end type",
        "    type :: logical_vector",
        "        integer(int64) :: index",
        "        logical :: value",
        "    end type",
        "    type :: int32_vector",
        "        integer(int64) :: index",
        "        integer(int32) :: value",
        "    end type",
        "",
        f"    integer(int32), parameter :: VEC_K = {v['K']}",
        f"    integer(int32), parameter :: VEC_KEY(4) = {words(v['key'])}",
    ]

    out += array("VEC_T", "type(t_vector)", [
        ctor("t_vector", [words(t[k]) for k in ("o", "h", "o_out", "h_out")]) for t in v["T"]
    ])
    for f in v["F"]:
        assert f["domain"] == "DOMAIN_STREAM" and f["aux"] == "AUX_STREAM"
    out += array("VEC_F", "type(f_vector)", [
        ctor("f_vector", [f"{f['counter']}_int64", words(f["o"]), words(f["h"])]) for f in v["F"]
    ])
    out += array("VEC_STREAM", "type(stream_vector)", [
        ctor("stream_vector", [f"{s['first_word']}_int64", words(s["words"])])
        for s in v["stream_words"]
    ])

    d = v["draws_from_position_0"]
    out += array("VEC_REAL64", "type(real64_vector)", [
        f"real64_vector({k}_int64, {real64(x)})" for k, x in d["Float64"].items()
    ])
    out += array("VEC_REAL32", "type(real32_vector)", [
        f"real32_vector({k}_int64, {real32(x)})" for k, x in d["Float32"].items()
    ])
    out += array("VEC_LOGICAL", "type(logical_vector)", [
        f"logical_vector({k}_int64, {'.true.' if x else '.false.'})" for k, x in d["Bool"].items()
    ])

    k = v["derived_keys"]
    out.append(f"    integer(int32), parameter :: VEC_SPLIT0(4) = {words(k['split_child_0'])}")
    out.append(f"    integer(int32), parameter :: VEC_SPLIT1(4) = {words(k['split_child_1'])}")
    out.append(f"    integer(int32), parameter :: VEC_FORK0(4) = {words(k['fork_child_0_at_block_0'])}")
    out.append(f"    integer(int32), parameter :: VEC_PURPOSE7(4) = {words(k['purpose_7'])}")

    s = v["seed_whitening"]
    out.append(f"    integer(int64), parameter :: VEC_SEED = {s['seed']}_int64")
    out.append(f"    integer(int32), parameter :: VEC_SEED_KEY(4) = {words(s['key'])}")
    out += array("VEC_SEED_REAL64", "type(real64_vector)", [
        f"real64_vector({kk}_int64, {real64(x)})" for kk, x in s["Float64"].items()
    ])
    out += array("VEC_SEED_INT32", "type(int32_vector)", [
        f"int32_vector({kk}_int64, {word(x)})" for kk, x in s["UInt32"].items()
    ])
    out.append("end module tandem_vectors")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
